### ISSUE TITLE
Installs "tests" and "tests_extra" top-level modules

### ISSUE THREAD

**Issue by wRAR** [scrapinghub/web-poet#106]
Running `pip install web-poet` also installs "tests" and "tests_extra" top-level modules:

```
$ ls -ld .env/lib/python3.10/site-packages/tests*
drwxr-xr-x 5 wrar wrar 100 ноя 11 17:36 .env/lib/python3.10/site-packages/tests
drwxr-xr-x 4 wrar wrar 100 ноя 11 17:36 .env/lib/python3.10/site-packages/tests_extra
```

I don't think it's intentional?

**Comment by Gallaecio** [comment]
I imagine https://github.com/scrapinghub/web-poet/blob/master/MANIFEST.in#L4 is including `tests`, despite https://github.com/scrapinghub/web-poet/blob/master/setup.py#L16.

I wonder if that line is also responsible for the inclusion of `test_extra`, though.

**Comment by wRAR** [comment]
I think `MANIFEST.in` only covers source archives and it's fine to incude tests there.
