### ISSUE TITLE
include more attributes on web_poet.page_inputs.ResponseData

### ISSUE THREAD

**Issue by BurnzZ** [scrapinghub/web-poet#17]
This issue aims to discuss adding new fields in addition to the existing `html` and `url` as proposed by @gatufo:

- cookies
- headers
- status_code

**Comment by kmike** [comment]
The reason for not having all these attributes in ResponseData was to have it minimal. 
For example, you can't get cookies from the current AutoExtract, and you can't get them from the current Zyte API as well. So, it'd mean that these APIs can't provide ResponseData. 

Status code is something which makes sense to add to ResponseData though.

I'm not sure about headers, probably better to keep them separate. 
Cookies - I'd definitely keep separate.

The idea was that these dependencies can be separate classes. If you request ResponseHeaders, providers can make sure that headers are returned - e.g. it may be a matter of including an additional argument to Zyte API, to return response headers.

As for cookies, we may have a situation where cookies are supported locally, but not in the API. It's easy to create Cookies dependency, and a provider for it in scrapy-poet, but to get the same thing from API may be difficult - it assumes API maintains cookies behind the scenes.

**Comment by kmike** [comment]
An advantage of having headers in ResponseData is that it'd make it easier to design an API to make additional requests in page objects. We can return ResponseData instances, and they'd contain all the response information.

**Comment by kmike** [comment]
I think this can be closed, because HttpResponse supports headers and status code. 

We may need a separate issue to discuss cookies. If that's about getting cookies from headers, it could be a method on Headers classes. But I think that's not what's most useful; it seems an access to the current cookiejar may be more important. But we need to think if that's a read-only access (is it useful?), or not. And if it's not read-only, is PO a best place to handle it. Many questions :)

**Comment by BurnzZ** [comment]
Yep, https://github.com/scrapinghub/web-poet/pull/30 covered headers and status code. 👍 

Regarding cookies, I'm also not sure if PO would be the right place to handle it. However, the cookiejar could be a dependency of the PO though. It could also perhaps be passed/represented inside the new `web_poet.page_inputs.Meta`.

I agree on closing this one now as the current state of web-poet covers all important cases already for this issue.
