### ISSUE TITLE
introduce more pages in addition to WebPage: JsonWebPage, CsvWebPage, etc

### ISSUE THREAD

**Issue by BurnzZ** [scrapinghub/web-poet#18]
This issue aims to discuss adding more page handlers as proposed by @gatufo.

----

Currently, we only have `web_poet.pages.WebPage` which supports selectors like `css()` and `xpath()` on HTML pages.

However, there are also other types of pages we could support:

- `JsonWebPage` which could have `jmespath` queries
- `CsvWebPage` which could have a "unified" way to read them _(usually used as seed data inputs in spiders)_
- `PlainTextWebPage` which could also have a "unified" way to read newline-separated data _(also usually use for seed URL inputs)_

**Comment by kmike** [comment]
If something like this is useful, it makes total sense to add it to web-poet. 
I'd start with an implementation in a project-specific repo, and then move commonly used code to web-poet.

**Comment by kmike** [comment]
Do you think we can close it, for the same reason as https://github.com/scrapinghub/web-poet/pull/25?

**Comment by BurnzZ** [comment]
@kmike , yes, we can re-open this one again later on should users ask for it.
