### ISSUE TITLE
Import some of the functionalities from autoextract_poet.item

### ISSUE THREAD

**Issue by BurnzZ** [scrapinghub/web-poet#21]
It appears that some users are using `autoextract_poet` without the intention of using https://docs.zyte.com/automatic-extraction.html. Interestingly, the only use case was to utilize these functionalities into their Page Object projects:

- [Item.from_dict()](https://github.com/scrapinghub/autoextract-poet/blob/master/autoextract_poet/items.py#L20)
- [_apply_types()](https://github.com/scrapinghub/autoextract-poet/blob/master/autoextract_poet/items.py#L44)

These functionalites offer the convenience of automaticallly converting the data format of the items for nested Items.

We might want to consider transferring such functionality into `web-poe` itself.

**Comment by kmike** [comment]
This code is now in https://github.com/zytedata/zyte-common-items, which is not related to Autoextract. I think we can close it.
