### ISSUE TITLE
Links pointing to same document

### ISSUE THREAD

**Issue by kishan3** [scrapinghub/web-poet#39]
Hello :wave:  
Please ignore if I understood it wrong.
When I check the doc [tutorial.rst](https://github.com/scrapinghub/web-poet/blob/master/docs/intro/tutorial.rst),
links like [from_ground_up](https://github.com/scrapinghub/web-poet/blame/67e72979bb7b56aebf7f0be07ea69131211eb8e9/docs/intro/tutorial.rst#L140), [scrapy:topics-index](https://github.com/scrapinghub/web-poet/blame/67e72979bb7b56aebf7f0be07ea69131211eb8e9/docs/intro/tutorial.rst#L136) are pointing to same `tutorial.rst`.
Should it point somewhere else or my understanding is wrong?

**Comment by BurnzZ** [comment]
Hi @kishan3 , everything seems to be in order here. Or perhaps I'm missing something. To clarify:

From the rendered docs in https://web-poet.readthedocs.io/en/stable/intro/tutorial.html#next-steps, what should be the expected links in it?

**Comment by kishan3** [comment]
> Hi @kishan3 , everything seems to be in order here. Or perhaps I'm missing something. To clarify:
> 
> From the rendered docs in https://web-poet.readthedocs.io/en/stable/intro/tutorial.html#next-steps, what should be the expected links in it?

HI @BurnzZ, I think you are right. I will close this issue.
