### ISSUE TITLE
Split documentation by target audience

### ISSUE THREAD

**Issue by Gallaecio** [scrapinghub/web-poet#54]
At the moment we kind of mix documentation for page object writers and for framework writers. I think it would be best to split the two at the root of the documentation, so that the top-level sections of the table of contents become:

1. Getting started
2. Writing page objects
3. Writing frameworks
4. Reference

So, for example, the content under “Framework expectations” in the “Additional requests” topic would be split into a separate page, under “Writing frameworks”.

**Comment by kmike** [comment]
Where would you put https://web-poet.readthedocs.io/en/latest/intro/from-ground-up.html? Is it for framework authors, is it a separate (5th) section, or is the idea to try to split it?

**Comment by Gallaecio** [comment]
I am not sure about touching anything under Getting Started as part of this split. I guess we could technically split off some bits of it into the framework development section, but if in doubt, I think it best to leave that page be.
