### ISSUE TITLE
Consider removing the limitation of only having a single PO in the registry

### ISSUE THREAD

**Issue by BurnzZ** [scrapinghub/web-poet#86]
Stemming off from the discussion in https://github.com/scrapinghub/web-poet/pull/84#discussion_r995643314.

**Comment by kmike** [comment]
Would it make sense to remove dict-like interface for PageObjectRegistry for 0.6.0 release? It seems it might get in a way if we want to implement this feature.

**Comment by BurnzZ** [comment]
Related threads:
- https://github.com/scrapinghub/web-poet/pull/96/files#r1009636014
- https://github.com/scrapinghub/web-poet/pull/96/files#r1010083865
